[package]
name = "sh-tauri"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.1.1", features = [] }

[dependencies]
serde_json.workspace = true
serde.workspace = true
tauri.workspace = true
tokio.workspace = true
sdrehub = { path = "../../libraries/sdrehub" }
sh-config = { path = "../../libraries/sh-config" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
