#!/command/with-contenv bash
# shellcheck shell=bash

# check the environment and see if there are any SH_* variables set
# if so, warn the user that they really should be mapping a file
# to /opt/sdre-hub-data and using /opt/sdre-hub-data/sh_config.toml

SH_DATA=$(env | grep '^SH_')

if [ -n "$SH_DATA" ]; then
  echo "[01-config-check] WARNING: You have SH_* environment variables set. You should be using a config file instead."
  echo "                  Please map a directory to /opt/sdre-hub-data and use /opt/sdre-hub-data/sh_config.toml"
fi

# check and see if /opt/sdre-hub-data/.empty exists. If it does, warn them that
# the dir isn't mapped and no data will be persisted between sessions

if [ -f /opt/sdre-hub-data/.empty ]; then
  echo "[01-config-check] WARNING: /opt/sdre-hub-data is not mapped. No data will be persisted between sessions."
fi

exit 0
