#!/command/with-contenv bash
# shellcheck shell=bash

if [[ ! -e /nginx-ranonce ]]; then
    cp /etc/nginx.sdrehub/sites-enabled/sdrehub /etc/nginx/sites-enabled/sdrehub || exit 1
    rm /etc/nginx/nginx.conf > /dev/null 2>&1  || exit 1
    cp /etc/nginx.sdrehub/nginx.conf /etc/nginx/nginx.conf || exit 1
    rm -rv /etc/nginx.sdrehub > /dev/null 2>&1 || exit 1
    rm /etc/nginx/sites-enabled/default > /dev/null 2>&1 || exit 1

    # turn off nginx logging
    # shellcheck disable=SC1003
    sed -i 's\access_log .*\access_log off;\' /etc/nginx/nginx.conf
    # shellcheck disable=SC1003
    sed -i 's\error_log .*\error_log /dev/null crit;\' /etc/nginx/nginx.conf
else
    if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
        echo "Skipping nginx file configuring, container was restarted" | awk '{print "[03-nginx    ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi
fi

touch /nginx-ranonce
