#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC2016
echo "Starting web proxy service" | stdbuf -oL awk '{print "[nginx       ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'


# shellcheck disable=SC2016
mkdir -p /var/log/nginx
# TODO: Run this via wiede's script
# shellcheck disable=SC2016
exec \
/usr/sbin/nginx 2>&1 | stdbuf -oL awk '{print "[nginx       ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
