#!/command/with-contenv bash
#shellcheck shell=bash

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

mkdir -p /var/log/nginx

"${s6wrap[@]}" /usr/sbin/nginx
