[package]
name = "sdre-hub"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
sdrehub = { path = "../../libraries/sdrehub" }
sh-config = { path = "../../libraries/sh-config" }
tokio = { version = "1.37.0", features = ["full", "tracing"] }
